-- liquibase formatted sql

-- changeset pipeb:1688955352772-1
CREATE TABLE "shorturl" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 612382) NOT NULL, "url" VARCHAR, "insert_time" date, CONSTRAINT "shorturl_pkey" PRIMARY KEY ("id"));

